name: Deploy to AWS

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    - name: Deploy Application
      run: |
        rsync -avz -e "ssh -i ~/.ssh/id_rsa" --exclude '.git/' --exclude '*.pem' ./ ubuntu@${{ secrets.EC2_IP }}:/var/www/html/
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          cd /var/www/html/server/  # Navigate to the correct directory
          # Ensure PM2 is installed
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi
          # Restart PM2 processes
          pm2 stop all || true
          pm2 start server.js --name server1 --time
          pm2 start dbServer.js --name server2 --time
          pm2 save
        EOF
